#!/usr/bin/env bash
# Install resmate and resmate-mcp from an extracted release archive in POSIX shells
# (macOS, Linux, or Git Bash on Windows).
#
# Usage:
#   ./install.sh [--prefix DIR] [--system] [--dry-run]
#
# Default (user-local, no sudo):
#   bin  -> $HOME/.local/bin
#   kit  -> $HOME/.local/share/resmate/templates
#   env  -> $HOME/.resmate/env

set -euo pipefail

PREFIX=""
SYSTEM=false
DRY_RUN=false

usage() {
  cat <<'EOF'
Usage: ./install.sh [--prefix DIR] [--system] [--dry-run]

  --prefix DIR   Install prefix (implies --system). Default system prefix: /usr/local
  --system       Install to $PREFIX or /usr/local (requires write access; may need sudo)
  --dry-run      Print actions without copying files

Default user-local install (no sudo):
  ~/.local/bin/resmate
  ~/.local/share/resmate/templates/
  ~/.resmate/env
EOF
  exit 1
}

while [[ $# -gt 0 ]]; do
  case "$1" in
    --prefix)
      PREFIX="$2"
      SYSTEM=true
      shift 2
      ;;
    --system)
      SYSTEM=true
      shift
      ;;
    --dry-run)
      DRY_RUN=true
      shift
      ;;
    -h|--help)
      usage
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage
      ;;
  esac
done

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"

RESMATE_SRC="$SCRIPT_DIR/bin/resmate"
MCP_SRC="$SCRIPT_DIR/bin/resmate-mcp"

# Windows release bundles contain .exe binaries; support Git Bash installs.
if [[ ! -f "$RESMATE_SRC" ]]; then
  RESMATE_SRC="$SCRIPT_DIR/bin/resmate.exe"
  MCP_SRC="$SCRIPT_DIR/bin/resmate-mcp.exe"
fi
if [[ ! -f "$RESMATE_SRC" || ! -f "$MCP_SRC" ]]; then
  echo "Error: run install.sh from the extracted release root (expected ./bin/resmate[.exe])." >&2
  exit 1
fi

if [[ "$SYSTEM" == true ]]; then
  INSTALL_ROOT="${PREFIX:-/usr/local}"
  BIN_DIR="$INSTALL_ROOT/bin"
  SHARE_DIR="$INSTALL_ROOT/share/resmate"
  ENV_FILE="$INSTALL_ROOT/etc/resmate/env"
else
  INSTALL_ROOT="${HOME}/.local"
  BIN_DIR="${HOME}/.local/bin"
  SHARE_DIR="${HOME}/.local/share/resmate"
  ENV_FILE="${HOME}/.resmate/env"
fi

TEMPLATE_DIR="$SHARE_DIR/templates"

run() {
  if [[ "$DRY_RUN" == true ]]; then
    echo "[dry-run] $*"
  else
    "$@"
  fi
}

# macOS Gatekeeper: browsers attach com.apple.quarantine to downloaded/extracted
# binaries. Without removing it, the first run may be blocked ("damaged" / unidentified).
strip_macos_quarantine() {
  local target="$1"
  if [[ "$(uname -s)" != "Darwin" ]]; then
    return 0
  fi
  if ! command -v xattr >/dev/null 2>&1; then
    return 0
  fi
  if [[ "$DRY_RUN" == true ]]; then
    echo "[dry-run] xattr -cr $target"
  else
    xattr -cr "$target" 2>/dev/null || true
  fi
}

echo "Installing ResMate CLI"
echo "  binaries -> $BIN_DIR"
echo "  templates -> $TEMPLATE_DIR"
echo "  env file -> $ENV_FILE"

run mkdir -p "$BIN_DIR" "$TEMPLATE_DIR" "$(dirname "$ENV_FILE")"

# Clear quarantine on release bundle binaries before copy (extract dir may be quarantined).
strip_macos_quarantine "$RESMATE_SRC"
strip_macos_quarantine "$MCP_SRC"

run cp "$RESMATE_SRC" "$MCP_SRC" "$BIN_DIR/"
if [[ "$DRY_RUN" != true ]]; then
  chmod 755 "$BIN_DIR/$(basename "$RESMATE_SRC")" "$BIN_DIR/$(basename "$MCP_SRC")"
fi

# cp preserves quarantine xattr; strip again on installed paths so resmate runs without manual xattr.
strip_macos_quarantine "$BIN_DIR/$(basename "$RESMATE_SRC")"
strip_macos_quarantine "$BIN_DIR/$(basename "$MCP_SRC")"

if [[ -d "$SCRIPT_DIR/share/resmate/templates" ]]; then
  run cp -a "$SCRIPT_DIR/share/resmate/templates/." "$TEMPLATE_DIR/"
else
  echo "Error: release bundle missing share/resmate/templates/" >&2
  exit 1
fi

if [[ "$DRY_RUN" == true ]]; then
  if [[ ! -d "$SCRIPT_DIR/share/resmate/templates/workspace" ]] \
    || [[ ! -d "$SCRIPT_DIR/share/resmate/templates/recipes" ]] \
    || [[ ! -f "$SCRIPT_DIR/share/resmate/templates/seed/resmate.yaml.tmpl" ]]; then
    echo "Error: release bundle missing required templates (workspace/, recipes/, seed/resmate.yaml.tmpl)." >&2
    exit 1
  fi
else
  if [[ ! -d "$TEMPLATE_DIR/workspace" ]] \
    || [[ ! -d "$TEMPLATE_DIR/recipes" ]] \
    || [[ ! -f "$TEMPLATE_DIR/seed/resmate.yaml.tmpl" ]]; then
    echo "Error: template tree incomplete after copy (need workspace/, recipes/, seed/resmate.yaml.tmpl)." >&2
    exit 1
  fi
fi

ENV_CONTENT="# ResMate CLI environment (generated by install.sh)
export RESMATE_TEMPLATES_DIR=\"$TEMPLATE_DIR\"
export PATH=\"$BIN_DIR:\$PATH\"
"

if [[ "$DRY_RUN" == true ]]; then
  echo "[dry-run] write $ENV_FILE"
  printf '%s' "$ENV_CONTENT"
else
  printf '%s' "$ENV_CONTENT" > "$ENV_FILE"
fi

append_source_hook() {
  local rc_file="$1"
  local hook='source "$HOME/.resmate/env"'
  if [[ "$SYSTEM" == true ]]; then
    return 0
  fi
  if [[ ! -f "$rc_file" ]]; then
    run touch "$rc_file"
  fi
  if [[ "$DRY_RUN" == true ]]; then
    echo "[dry-run] ensure hook in $rc_file"
    return 0
  fi
  if ! grep -Fq '.resmate/env' "$rc_file" 2>/dev/null; then
    {
      echo ''
      echo '# ResMate CLI'
      echo "$hook"
    } >> "$rc_file"
    echo "Added source hook to $rc_file"
  fi
}

if [[ "$SYSTEM" != true ]]; then
  append_source_hook "${HOME}/.zshrc"
  append_source_hook "${HOME}/.bashrc"
fi

cat <<EOF

ResMate installed successfully.

Next steps:
  1. Reload your shell:  source "$ENV_FILE"
  2. Verify:             resmate --help
  3. Bootstrap workspace:
       mkdir ~/my-use-case && cd ~/my-use-case
       resmate init --name my-use-case

See docs/QUICKSTART.md in this archive for the full flow.

EOF
